In [91]:
import numpy as np
import pandas as pd

In [92]:
data={
    'Name':['john','Aman','Peter','Linda'],
    'Age':[23,34,45,56],
    'city':['new york','paris','london','berlin'],
    'salary':[2000,3000,5000,600]
}
d=pd.DataFrame(data)

In [93]:
d

    Name  Age      city  salary
0   john   23  new york    2000
1   Aman   34     paris    3000
2  Peter   45    london    5000
3  Linda   56    berlin     600

In [94]:
data=[
    ['john','Aman','Peter','Linda'],
    [23,34,45,56],
    ['new york','paris','london','berlin'],
    [2000,3000,5000,600]
]
row=['name','age','city','salary']
d2=pd.DataFrame(data)
d2=pd.DataFrame(data,row)

In [95]:
d2

               0      1       2       3
name        john   Aman   Peter   Linda
age           23     34      45      56
city    new york  paris  london  berlin
salary      2000   3000    5000     600

In [96]:
d2.loc['name']

0     john
1     Aman
2    Peter
3    Linda
Name: name, dtype: object

In [97]:
data_list=[
['john',20,'new york',6500],
['anna',28,'paris',3456],
['peter',34,'berlin',62000],
['linda',42,'london',84000]
]
d3=pd.DataFrame(data_list)
column=['name','age','city','salary']
d3=pd.DataFrame(data_list,columns=column)

In [98]:
d3

    name  age      city  salary
0   john   20  new york    6500
1   anna   28     paris    3456
2  peter   34    berlin   62000
3  linda   42    london   84000

In [99]:
d3['name']

0     john
1     anna
2    peter
3    linda
Name: name, dtype: str

In [100]:
d3

    name  age      city  salary
0   john   20  new york    6500
1   anna   28     paris    3456
2  peter   34    berlin   62000
3  linda   42    london   84000

In [101]:
d3["Designation"]=["doctor","eng","doc","ram"]

In [102]:
d3

    name  age      city  salary Designation
0   john   20  new york    6500      doctor
1   anna   28     paris    3456         eng
2  peter   34    berlin   62000         doc
3  linda   42    london   84000         ram

In [103]:
d3.drop('Designation',axis=1,inplace=True)

In [104]:
d3

    name  age      city  salary
0   john   20  new york    6500
1   anna   28     paris    3456
2  peter   34    berlin   62000
3  linda   42    london   84000

In [105]:
d3

    name  age      city  salary
0   john   20  new york    6500
1   anna   28     paris    3456
2  peter   34    berlin   62000
3  linda   42    london   84000

In [106]:
d3.loc[[0,1]]

   name  age      city  salary
0  john   20  new york    6500
1  anna   28     paris    3456

In [107]:
d3.iloc[0]

name          john
age             20
city      new york
salary        6500
Name: 0, dtype: object

In [108]:
d3

    name  age      city  salary
0   john   20  new york    6500
1   anna   28     paris    3456
2  peter   34    berlin   62000
3  linda   42    london   84000

In [109]:
d3.loc[[0,1]][["city","salary"]]

       city  salary
0  new york    6500
1     paris    3456

In [110]:
d3.loc[[2,3]][["name","age"]]

    name  age
2  peter   34
3  linda   42

In [111]:
d3

    name  age      city  salary
0   john   20  new york    6500
1   anna   28     paris    3456
2  peter   34    berlin   62000
3  linda   42    london   84000

In [112]:
d3[(d3["age"]>30) & (d3["city"]=="london")]

    name  age    city  salary
3  linda   42  london   84000