In [1]:
import numpy as np
import pandas as pd

In [2]:
employees=pd.DataFrame({
    'employee_id':[1,2,3,4,5],
    'name':['john','anna','peter','linda','bob'],
    'departement':['hr','it','finance','it','hr']
})
salaries=pd.DataFrame({
    'employee_id':[1,2,3,6,7],
    'salary':[500,600,800,900,1000],
    'bonus':[5000,4000,7000,8000,12000]
})

In [3]:
employees

   employee_id   name departement
0            1   john          hr
1            2   anna          it
2            3  peter     finance
3            4  linda          it
4            5    bob          hr

In [4]:
salaries

   employee_id  salary  bonus
0            1     500   5000
1            2     600   4000
2            3     800   7000
3            6     900   8000
4            7    1000  12000

In [5]:
pd.merge(employees,salaries)

   employee_id   name departement  salary  bonus
0            1   john          hr     500   5000
1            2   anna          it     600   4000
2            3  peter     finance     800   7000

In [6]:
pd.merge(employees,salaries,on='employee_id',how='inner')

   employee_id   name departement  salary  bonus
0            1   john          hr     500   5000
1            2   anna          it     600   4000
2            3  peter     finance     800   7000

In [7]:
pd.merge(employees,salaries,on='employee_id',how='outer')

   employee_id   name departement  salary    bonus
0            1   john          hr   500.0   5000.0
1            2   anna          it   600.0   4000.0
2            3  peter     finance   800.0   7000.0
3            4  linda          it     NaN      NaN
4            5    bob          hr     NaN      NaN
5            6    NaN         NaN   900.0   8000.0
6            7    NaN         NaN  1000.0  12000.0

In [8]:
df1=pd.DataFrame({
    'A':['A0','A1','A2'],
    'B':['B0','B1','B2'],
    'C':['C0','C1','C2']
})
df2=pd.DataFrame({
    'A':['A3','A4','A5'],
    'B':['B3','B4','B5'],
    'C':['C3','C4','C5']
})

In [12]:
df1

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [17]:
df2

    A   B   C
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [20]:
pd.concat([df1,df2])

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [26]:
pd.concat([df1,df2],axis=1)

    A   B   C   A   B   C
0  A0  B0  C0  A3  B3  C3
1  A1  B1  C1  A4  B4  C4
2  A2  B2  C2  A5  B5  C5

In [27]:
df1=pd.DataFrame({
    'name':['Alice','Bob','Charlie']
},index=[1,2,3,])
df2=pd.DataFrame({
    'score':[85,90,75]
},index=[2,3,4])

In [28]:
df1

      name
1    Alice
2      Bob
3  Charlie

In [29]:
df2

   score
2     85
3     90
4     75

In [30]:
df1.join(df2)

      name  score
1    Alice    NaN
2      Bob   85.0
3  Charlie   90.0

In [31]:
df1.join(df2,how='outer')

      name  score
1    Alice    NaN
2      Bob   85.0
3  Charlie   90.0
4      NaN   75.0