In [1]:
import numpy as np
import pandas as pd

In [2]:
data={
    'A':[1,2,np.nan,4,5],
    'B':[np.nan,2,3,4,5],
    'C':[1,2,3,np.nan,np.nan],
    'D':[1,np.nan,np.nan,np.nan,5]
}
df=pd.DataFrame(data)

In [3]:
df

     A    B    C    D
0  1.0  NaN  1.0  1.0
1  2.0  2.0  2.0  NaN
2  NaN  3.0  3.0  NaN
3  4.0  4.0  NaN  NaN
4  5.0  5.0  NaN  5.0

In [4]:
df.isna()

       A      B      C      D
0  False   True  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [5]:
df.isna().sum()

A    1
B    1
C    2
D    3
dtype: int64

In [6]:
df.isna().any()

A    True
B    True
C    True
D    True
dtype: bool

In [7]:
data={
    'A':[1,2,np.nan,4,5],
    'B':[1,2,3,4,5],
    'C':[1,2,3,np.nan,np.nan],
    'D':[1,np.nan,np.nan,np.nan,5]
}
d4=pd.DataFrame(data)

In [8]:
d4

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [9]:
d4.dropna()

     A  B    C    D
0  1.0  1  1.0  1.0

In [10]:
d4.dropna(thresh=3)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
4  5.0  5  NaN  5.0

In [11]:
d4.fillna(0)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  0.0
2  0.0  3  3.0  0.0
3  4.0  4  0.0  0.0
4  5.0  5  0.0  5.0

In [12]:
values={'A':0,'B':12,'C':23,'D':34}
d4.fillna(value=values)

     A  B     C     D
0  1.0  1   1.0   1.0
1  2.0  2   2.0  34.0
2  0.0  3   3.0  34.0
3  4.0  4  23.0  34.0
4  5.0  5  23.0   5.0