In [82]:
import numpy as np
import pandas as pd

In [83]:
data={
    'name':['john','Anna','peter','linda'],
    'age':[23,34,45,56],
    'city':['new york','london','berlin','paris'],
    'salary':[3000,4000,5000,6000]
}
pd.DataFrame(data)

    name  age      city  salary
0   john   23  new york    3000
1   Anna   34    london    4000
2  peter   45    berlin    5000
3  linda   56     paris    6000

In [84]:
data_list=[
    ['john',65,'new york',65000],
    ['Anna',34,'paris',45000],
    ['peter',56,'berlin',5000],
    ['linda',42,'london',56000]
]
df2=pd.DataFrame(data_list)
column=['name','age','city','salary']
df2=pd.DataFrame(data_list,columns=column)

In [85]:
df2

    name  age      city  salary
0   john   65  new york   65000
1   Anna   34     paris   45000
2  peter   56    berlin    5000
3  linda   42    london   56000

In [86]:
df2

    name  age      city  salary
0   john   65  new york   65000
1   Anna   34     paris   45000
2  peter   56    berlin    5000
3  linda   42    london   56000

In [87]:
df2[['age','city']]

   age      city
0   65  new york
1   34     paris
2   56    berlin
3   42    london

In [88]:
df2["Designation"]=["doctor","eng","doctor","eng"]

In [89]:
df2

    name  age      city  salary Designation
0   john   65  new york   65000      doctor
1   Anna   34     paris   45000         eng
2  peter   56    berlin    5000      doctor
3  linda   42    london   56000         eng

In [90]:
df2.drop('Designation',axis=1,inplace=True)

In [91]:
df2

    name  age      city  salary
0   john   65  new york   65000
1   Anna   34     paris   45000
2  peter   56    berlin    5000
3  linda   42    london   56000

In [96]:
df2

    name  age      city  salary
0   john   65  new york   65000
1   Anna   34     paris   45000
2  peter   56    berlin    5000
3  linda   42    london   56000

In [97]:
df2.loc[[0,1]]

   name  age      city  salary
0  john   65  new york   65000
1  Anna   34     paris   45000

In [98]:
df2.loc[[0,1,]][['city','salary']]

       city  salary
0  new york   65000
1     paris   45000

In [99]:
df2.loc[[2,3]][['name','age']]

    name  age
2  peter   56
3  linda   42

In [104]:
df2[(df2['age']>30) & (df2['city']=='paris')]

   name  age   city  salary
1  Anna   34  paris   45000

In [107]:
data={
    'A':[1,2,np.nan,4,5],
    'B':[np.nan,2,3,4,5],
    'C':[1,2,3,np.nan,np.nan],
    'D':[1,np.nan,np.nan,np.nan,5]
}
df=pd.DataFrame(data)

In [119]:
df.isna().sum()

A    1
B    1
C    2
D    3
dtype: int64

In [113]:
df.dropna(thresh=3)

     A    B    C    D
0  1.0  NaN  1.0  1.0
1  2.0  2.0  2.0  NaN
4  5.0  5.0  NaN  5.0

In [114]:
df

     A    B    C    D
0  1.0  NaN  1.0  1.0
1  2.0  2.0  2.0  NaN
2  NaN  3.0  3.0  NaN
3  4.0  4.0  NaN  NaN
4  5.0  5.0  NaN  5.0

In [116]:
df.fillna(0)

     A    B    C    D
0  1.0  0.0  1.0  1.0
1  2.0  2.0  2.0  0.0
2  0.0  3.0  3.0  0.0
3  4.0  4.0  0.0  0.0
4  5.0  5.0  0.0  5.0

In [117]:
value={'A':0,'B':100,'C':300,'D':400}
df.fillna(value=value)

     A      B      C      D
0  1.0  100.0    1.0    1.0
1  2.0    2.0    2.0  400.0
2  0.0    3.0    3.0  400.0
3  4.0    4.0  300.0  400.0
4  5.0    5.0  300.0    5.0

In [120]:
employees=pd.DataFrame({
    'employee_id':[1,2,3,4,5],
    'name':['john','Anna','peter','Linda','bob'],
    'department':['HR','IT','Finance','It','HR']
})
salaries=pd.DataFrame({
    'employee_id':[1,2,3,6,7],
    'salary':[6000,8000,65000,7000,9000],
    'bonus':[5000,10000,7000,8000,120000]
})

In [121]:
employees

   employee_id   name department
0            1   john         HR
1            2   Anna         IT
2            3  peter    Finance
3            4  Linda         It
4            5    bob         HR

In [122]:
salaries

   employee_id  salary   bonus
0            1    6000    5000
1            2    8000   10000
2            3   65000    7000
3            6    7000    8000
4            7    9000  120000

In [ ]:
pd.merge(employees,salaries,on='employee_id')

   employee_id   name department  salary  bonus
0            1   john         HR    6000   5000
1            2   Anna         IT    8000  10000
2            3  peter    Finance   65000   7000

In [124]:
pd.merge(employees,salaries,on='employee_id',how='inner')

   employee_id   name department  salary  bonus
0            1   john         HR    6000   5000
1            2   Anna         IT    8000  10000
2            3  peter    Finance   65000   7000

In [125]:
pd.merge(employees,salaries,on='employee_id',how='outer')

   employee_id   name department   salary     bonus
0            1   john         HR   6000.0    5000.0
1            2   Anna         IT   8000.0   10000.0
2            3  peter    Finance  65000.0    7000.0
3            4  Linda         It      NaN       NaN
4            5    bob         HR      NaN       NaN
5            6    NaN        NaN   7000.0    8000.0
6            7    NaN        NaN   9000.0  120000.0